### ISSUE TITLE
Feedback for Milestone 3

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/Marshall_violent_crimes#26]
Good job overall - the app is looking a lot better with a lot more information on offer

There are some minor issues related to the format of years displayed in the slider and the top ten feature in your list of cities not having an effect on the data viz

I'd recommend a few more descriptive titles for code chunks, and double checking redundant lines of code, 
but otherwise your code is very neat and clean.

**Comment by akanshaVashisth** [comment]
Thank you for the feedback Sahir.
We have implemented the suggested changes. Now the app looks even better.
