### ISSUE TITLE
Milestone 1: Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/Marshall_violent_crimes#9]
Overall your description of the app and sketch were good.

It would have been better is you had included a little more information or detail in your description of the data and the app. For eg, it wasnt very clear until I read it a second time that the landing page would change to the four graphs only when the user entered the names of cities s/he was thinking of moving to. From an initial look at your sketch I was under the impression that this was going to be a separate tab. 

Other than that minor point and a few grammatical errors, everything else was good.

**Comment by akanshaVashisth** [comment]
Thank you for the feedback.

We will keep in mind to add a detailed description of the app in the write-up and will try to provide information to the user for effectively using the app.
